AWSTemplateFormatVersion: "2010-09-09"
Description: "EC2 Instance with User Data"

Resources:
  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-06b72b3b2a773be2b"
      InstanceType: "t2.micro"
      KeyName: "formaskypem"
      SecurityGroupIds:
        - "sg-09090b2fb912a8caa"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "<h1>Hello Guys This is  MyEC2Instance</h1>" > /var/www/html/index.html
      Tags:
        - Key: "Name"
          Value: "MyEC2Instance"
